### ISSUE TITLE
stuck in while loop

### ISSUE THREAD

**Issue by kaishi78** [ARMmbed/mbed-client-c#118]
When I passing in the following get request for 10245/0/101:
40 01 00 00 b5 31 30 32 34 35 01 30 03 31 30 31 00 00 00 00 00 00 00 00 00 00 00 00 

I get stuck in sn_coap_parser_options_parse() because of the trailing zeros.

If the message was with out the trailing zeros:
40 01 00 00 b5 31 30 32 34 35 01 30 03 31 30 31

it works fine.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1439

**Comment by JanneKiiskila** [comment]
Hi @kaishi78 

Clearly looks a bug in our implementation then, we will take this to our backlog and start looking into a fix.

Thank You for reporting this issue!

**Comment by kjbracey-arm** [comment]
Just to note, that to me reads as a request for "10245/0/101////////////", unless I'm mistaken - those trailing zeros do have a meaning.

Not that that excuses a lockup, but bear in mind while fixing.

**Comment by JanneKiiskila** [comment]
Fix available in; https://github.com/ARMmbed/mbed-coap/pull/4

**Comment by JanneKiiskila** [comment]
Fix is now also merged to mbedOS 5.4 branch.
https://github.com/ARMmbed/mbed-os/commit/fd5c327de136269a66f547d8729686f350d516cd
