### ISSUE TITLE
Link in mbed-coap.lib does not exists

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client-c#127]
The mbed-coap.lib in this repository links to a not existing CoAP repository:

[https://github.com/ARMmbed/mbed-coap/#12c87e057e0c6fef523457cd04651fdc9412901f](url)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1510

**Comment by anttiylitokola** [comment]
Hi, Can you try again now?

**Comment by EduardPon** [comment]
No, I still get a page not found 404 error.

**Comment by EduardPon** [comment]
It works! Thanks...
