### ISSUE TITLE
Use updated module version definitions

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/mbed-client-c#3]
`sn_nsdl_get_version` should use `YOTTA_MBED_CLIENT_C_VERSION_STRING` instead of the deprecated `YOTTA_COMPONENT_VERSION`

The `YOTTA_COMPONENT_VERSION` definition has been deprecated in favour of a more granular set of version definitions:

https://github.com/autopulated/yotta/blob/remove-deprecated-version-def/docs/tutorial/release.md#embedded-version-numbers

I'd like to remove `YOTTA_COMPONENT_VERSION` from the next yotta release (before we release publicly), as it is can be quite visible in compiler command lines, but should not be used.

I think this module is the only one still using it.

**Comment by AnttiKauppila** [comment]
This has been updated
