### ISSUE TITLE
Allow for config of SN_COAP_DUPLICATION_MAX_MSGS_COUNT using yotta config

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client-c#31]
We have seen problems with retransmitted packets triggering actions twice. Enabling the deduplication logic would require us to fork mbed-client-c, because you cannot use yotta config to modify it ATM.

**Comment by yogpan01** [comment]
Hi, Can you please elaborate on your use case ? What are you trying to achieve here ? This configuration is not enabled on yotta level yet because we didn't have the use case yet so even if we provide enabling this config, we would need to test this case.

**Comment by markus-becker-tridonic-com** [comment]
At the moment, it seems the stack by default is not filtering duplicate CoAP packets out. At least we've seen duplicate messages with the same ID being delivered to the application, resulting toggle actions being acted upon twice.
We assume that the stack would do the filtering when defining SN_COAP_DUPLICATION_MAX_MSGS_COUNT non zero. Would be good to be able to yotta config it, since it has an impact on RAM/ROM size, or?

**Comment by yogpan01** [comment]
Yes, currently there is no yotta config for this, we can add this parameter in mbed-client-c. We will update this issue when we add this feature flag .

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-621

**Comment by mlnx** [comment]
Update: this is planned for the next sprint. If everything goes well, it will be released after that.

**Comment by markus-becker-tridonic-com** [comment]
When does the sprint start? How long are your sprints?

Markus

**Comment by anttiylitokola** [comment]
Hi, 
We will start working on this next week and this shouldn't be a big task to complete. I'll update this issue once the change is published, should be ready by the end of the next week.

**Comment by anttiylitokola** [comment]
Hi Markus,

There is now version that allows to change duplication message count via yotta configuration system. It's released in mbed-client-c version 2.3.2. 

To enable message duplication, you need to create a config.json file in the application level.
An example:
{
"coap_duplication_max_msgs_count": 1
}

Please, let us know if this solves your original issue.

**Comment by markus-becker-tridonic-com** [comment]
Gre. Thanks.
