### ISSUE TITLE
mbed-client-c porting

### ISSUE THREAD

**Issue by rajbatra** [ARMmbed/mbed-client-c#36]
Hi i was not able to find any example or porting guide for mbed -client-c like we have for mbed-client which are written in c++.
Can you please provide any porting guide link or example using mbed-client-c libraries as well as link to the api documentation.

Regards

**Comment by yogpan01** [comment]
Hi, there isn't any porting guide for mbed-client-c. mbed-client-c is used by mbed-client API to provide LWM2M feature set. Its an internal library and doesn't contain any logic for connectivity or managing L2M2M resources.

**Comment by rajbatra** [comment]
so that means it is mostly device independent and can be ported easily to other platforms like FreeRTOS?
Do you have any example on how to use it and any API documentation available.

**Comment by yogpan01** [comment]
Hi, Can you define your use case ? Is there any issue in using mbed Client APIs.

**Comment by rajbatra** [comment]
Actually we would like to use mbed-client-c libraries to FreeRTOS so we just wanted to know if there are any interdependencies need to be taken care.

**Comment by yogpan01** [comment]
You can use mbed-client-c if you are planning to handle all the other platform dependencies yourself.
Otherwise you can port mbed Client C++ APIs for freeRTOS just like those are available for Linux and mbed OS currently.

**Comment by rajbatra** [comment]
We will handle the rest of the dependencies.However we need some documentation over the API's.Can you please provide the link for the API's documentation

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-704

**Comment by shanmugav** [comment]
Can you tell me how to run the mbed-client-c test example: multithread-linux-test? How to view the result in mbed cloud server like we see it for mbed-client C++ linux test example?

**Comment by yogpan01** [comment]
mbed-client-c is an independent module which doesn't connect to mbed cloud server because its not supporting DTLS connectivity. Applications using mbed-client-c must implement their own connectivity and secure connection logic.

**Comment by shanmugav** [comment]
Can you share detailed steps on how to test mbed-client-c. I understand that mbed-client-c doesn't have DTLS support.

My assumption is

1. Add  openssl (or some other SSL) support
2. do a SSL connect with security key obtained from my account in mbed.
3. Now the status should show active on the server in my web page and we are ready to go.

I would like to add support on the same, please confirm and elaborate more if there is any ambiguity.

**Comment by shanmugav** [comment]
Another question just came into picture is, do we need DTLS or is TLS alone is sufficient? like open-ssl and do a SSL-TCP connect using TLS.

**Comment by yogpan01** [comment]
Hi,
The steps you mentioned for adding ssl and connectivity to add on top of mbed-client-c are correct.
As for using SSL-TCP and TLS, it can be done but then since mbed-client-c is based on CoAP (which in turn in based on UDP) , you would need to do some additional data-header length shiming before you can have a successful TCP pipe. You can refer to our source code , to see how to have CoAP on TCP implementation (example from Linux porting) from here
https://github.com/ARMmbed/mbed-client-linux/blob/master/source/m2mconnectionhandlerpimpl.cpp#L277
