### ISSUE TITLE
blockwise transfer for payloads bigger than RAM size

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client-c#39]
At the moment, it seems blockwise transfer in mbed-client-c only allows for transfer of payloads which in total fit into RAM since all chunks are put into a linked list ( https://github.com/ARMmbed/mbed-client-c/blob/master/source/libCoap/src/include/sn_coap_protocol_internal.h#L151 ). Firmware images are likely to be bigger than RAM. What is the mechanism to inform the application about individual chunks, so that the application could put the chunks into internal or external flash one by one?
`

**Comment by markus-becker-tridonic-com** [comment]
FYI @mlnx

**Comment by yogpan01** [comment]
Hi, There is a need for providing possibility for application to provide their own memory blocks to handle this case. It is an extension feature that is planned to be implemented. We haven't yet figured out the complete details, if you have any suggestions that you would like to see , please share and we can take that into consideration.

**Comment by markus-becker-tridonic-com** [comment]
I think the handle should have sn_coap_rx_callback_block_chunk() which if set should be called with information about the chunk number, size and payload (possibly also source port and address).  The writing of the chunk to flash should block the transmission of further chunks.

Would be good if this could be combined with the LWM2M object for Firmware Update.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-729

**Comment by yogpan01** [comment]
Thanks for the suggestion. It makes sense to have an API on Firmware Update class to pass the callback function pointer, as well as add a new API on mbed-client-c to support this feature at both layers.

**Comment by zhang405744522** [comment]
mbed client blockwise do not work

**Comment by anttiylitokola** [comment]
Feature is now available and documentation how it can be used can be found from mbed-client examples and documentation page.
https://docs.mbed.com/docs/mbed-client-guide/en/latest/Howto/#how-to-create-and-configure-resources-and-resource-instances "Setting an external handler for block-wise messages".
