### ISSUE TITLE
mbed client blockwise do not work

### ISSUE THREAD

**Issue by zhang405744522** [ARMmbed/mbed-client-c#43]
mbed client blockwise do not work

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-744

**Comment by yogpan01** [comment]
Hi, Can you please elaborate , what exactly didnt work for you ?
You can check https://docs.mbed.com/docs/mbed-client-guide/en/latest/Introduction/ , section Maximum UDP message size, on how to get blockwise working..

**Comment by anttiylitokola** [comment]
Hi, we have published several fixes for blockwise feature. Can you try to fetch latest modules through yotta and see is it working any better? I'll close this ticket now but feel free to open it if you are still experiencing issues with blockwise operation.
