### ISSUE TITLE
Feature request: Multicast message resend to improve reliability

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client-c#51]
I have a feature request. It would be nice to have a 'always re-send **multicast** message' to improve reliability with cabled connection, with a configurable number of re-sends and time interval. The resend message should be an exact copy of the initial message. Hereby receiver(s) can detect duplication of messages by checking the message ID and avoid reprocessing of POST messages.    

Most of this implementation is already available to resend messages in case of missing acknowledges: 
o   Timing/scheduled based execution to perform re-sends.
o   CoAP implementation caches elementary messages that must be repeated.
o   Application can already configure number of re-sends and time interval of the CoAP resends (`sn_nsdl_set_retransmission_parameters`)
1. I propose to add an API function to enable/disable the proposed resend for multicast messages.
2. Proposed: change the function `sn_coap_protocol_build` to cache also the a multicast CoAP message (`sn_coap_protocol_linked_list_send_msg_store(..)`):

```
if( (src_coap_msg_ptr->msg_type == COAP_MSG_TYPE_CONFIRMABLE) || multicast_resend_duplicate )
{
    /* Store message to Linked list for resending purposes */
    sn_coap_protocol_linked_list_send_msg_store(handle, dst_addr_ptr, byte_count_built, dst_packet_data_ptr,
           handle->system_time + (uint32_t)(handle->sn_coap_resending_intervall * RESPONSE_RANDOM_FACTOR),
           param, src_coap_msg_ptr->uri_path_ptr, src_coap_msg_ptr->uri_path_len);
}
```

Please let me know if this feature request can implemented. Thanks in advance.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-778

**Comment by EduardPon** [comment]
Hello,

This is my proposed API extensions:

sn_nsdl_lib.h
```
/**
 * \fn int8_t sn_nsdl_set_non_confirmable_resent_parameters(bool enable_resent)
 *
 * \brief  If re-transmissions are enabled (see also sn_nsdl_set_retransmission_parameters),
 *         this function enables/disables a resent of a non confirmable message. This
 *         improves the transmission reliability by duplicating the message (including
 *         header). The CoAP protocol at receiver side will recognize the duplications
 *         and discards the redundant messages.
 *
 * \param bool enable_resent when set to resent non confirmable messages
 * \return  0 = success, -1 = failure
 */
extern int8_t sn_nsdl_set_non_confirmable_resent_parameters(struct nsdl_s *handle, bool enable_resent);
```
sn_coap_protocol.h
```
/**
 * \fn int8_t sn_coap_protocol_set_non_confirmable_resent_parameters(bool enable_resent)
 *
 * \brief  If re-transmissions are enabled (see also sn_nsdl_set_retransmission_parameters),
 *         this function enables/disables a resent of a non confirmable message. This
 *         improves the transmission reliability by duplicating the message (including
 *         header). The CoAP protocol at receiver side will recognize the duplications
 *         and discards the redundant messages.
 *
 * \param bool enable_resent when set to resent non confirmable messages
 * \return  0 = success, -1 = failure
 */
extern int8_t sn_coap_protocol_set_non_confirmable_resent_parameters(struct coap_s *handle,
        bool enable_resent);
```
sn_coap_protocol_internal.h added extra boolean in struct coap_s { 
`bool resent_non_confirmable; /* Can be modified by sn_nsdl_set_retransmission_parameters, to perform always a resent for non confirmable messages */`


Implementation extensions:

sn_nsdl.c
```
extern int8_t sn_nsdl_set_non_confirmable_resent_parameters(struct nsdl_s *handle,
    bool enable_resent)
{
    if (handle == NULL) {
        return SN_NSDL_FAILURE;
    }
    return sn_coap_protocol_set_non_confirmable_resent_parameters(handle->grs->coap,
                                                                  enable_resent);
}
```
sn_coap_protocol.c
```
int8_t sn_coap_protocol_set_non_confirmable_resent_parameters(struct coap_s *handle,
        bool enable_resent)
{
#if ENABLE_RESENDINGS
    if (handle == NULL) {
        return -1;
    }

    handle->resent_non_confirmable = enable_resent;

    return 0;

#endif
    return -1;
}
```
sn_coap_protocol.c
Added code  ((src_coap_msg_ptr->msg_type == COAP_MSG_TYPE_NON_CONFIRMABLE) && (handle->resent_non_confirmable)) ) 
```
#if ENABLE_RESENDINGS /* If Message resending is not used at all, this part of code will not be compiled */

    /* Check if built Message type was confirmable, only these messages are resent when not acknowledged.
       NON confirmable messages can be queued when sn_nsdl_set_retransmission_parameters() explicit requests to perform a scheduled resent */
    if( (src_coap_msg_ptr->msg_type == COAP_MSG_TYPE_CONFIRMABLE) ||
        ((src_coap_msg_ptr->msg_type == COAP_MSG_TYPE_NON_CONFIRMABLE) && (handle->resent_non_confirmable)) ) {
        /* Store message to Linked list for resending purposes */
        sn_coap_protocol_linked_list_send_msg_store(handle, dst_addr_ptr, byte_count_built, dst_packet_data_ptr,
                handle->system_time + (uint32_t)(handle->sn_coap_resending_intervall * RESPONSE_RANDOM_FACTOR),
                param, src_coap_msg_ptr->uri_path_ptr, src_coap_msg_ptr->uri_path_len);
    }

#endif /* ENABLE_RESENDINGS */
```

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
