### ISSUE TITLE
Random CoAP message ID

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client-c#59]
Why is time() used for seeding the RNG? This only properly works on RTC enabled devices. It should now be seeded using arm_random_seed_get(void), or? 

Then randLIB_get_8bit() could be used in sn_coap_protocol.c:sn_coap_protocol_init()
https://github.com/ARMmbed/mbed-client-c/blob/master/source/libCoap/src/sn_coap_protocol.c#L202.

@mlnx

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-828

**Comment by mlnx** [comment]
@sbutcher-arm could you please provide an answer for this?

**Comment by yogpan01** [comment]
@mlnx This is mbed-client component, we can update this . I will put this into our backlog and provide fix.

**Comment by markus-becker-tridonic-com** [comment]
Is there an ETA for this feature/fix?

**Comment by yogpan01** [comment]
Hi,
We need to study this solution a bit more because we need to see the impact of using arm_random_seed_get(void) directly. This component is fairly platform independent and we need to check if we are not introducing any hard dependency by using this API directly.
We are also pressed with other items in our backlog so this will take few more weeks before we resolve it. We will however try to speed up this issue for early resolution.

@mlnx

**Comment by kjbracey-arm** [comment]
As a library module, seeding should not be mbed-client-c's problem - it makes sense to simply use rand() or randLIB_get_16bit(), in both cases on the assumption that the system/application initialisation has already taken care of appropriate seeding.

I'm not sure whether randLIB is treated as part of mbed-client-c's HAL expectation, but I would have thought it makes sense to do so.

(randLIB_get_16bit seems the appropriate choice here - not sure why it restricts itself to a range of 400 at the moment. And randLIB_get_16bit also covers the possibility of rand() only returning a 15-bit number).

I am aware though that some parts of the mbed client stack have been trying to do their own workarounds for lack of correct seeding on some systems - this may be part of that.

**Comment by markus-becker-tridonic-com** [comment]
@MarceloSalazar what is the status of this in mbed5?

**Comment by yogpan01** [comment]
Hi, There is randomization API that we can use randLIB_get_16bit() but this has to be instantiated by some application , we are trying to find the right component which could do the seeding and then we can use this API. We will take this up now and try to resolve it in a way that it is backward compatible as well as platform compatible (ie. works on non mbed OS platform as well)

**Comment by simosillankorva** [comment]
Hi,
I have created a pull request https://github.com/ARMmbed/mbed-client-c/pull/91, that should fix this issue by using randLIB component (https://github.com/ARMmbed/mbed-client-randlib) for the message ID randomization. 

This library calls platform spesific function "uint32_t arm_random_seed_get(void)" to seed the random when initialized. Alternatively it can be also seeded by calling "void randLIB_add_seed(uint64_t seed)".

@markus-becker-tridonic-com could you please check if this fixes the issue?

**Comment by MarceloSalazar** [comment]
@markus-becker-tridonic-com could you please check if this fixes the issue?

**Comment by markus-becker-tridonic-com** [comment]
@MarceloSalazar Yes. this is perfect. Please merge as soon as possible.

**Comment by simosillankorva** [comment]
@markus-becker-tridonic-com @MarceloSalazar The fix has now been merged.
